- name: activity-add
  color: 0e8a16
  description: 新增活动信息
- name: activity-update
  color: fbca04
  description: 修改活动信息
- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: help wanted
  color: 008672
  description: Extra attention is needed
