# 允许用户在模板之外创建空白 Issue
blank_issues_enabled: true

# 在 Issue 选择页面添加一个自定义链接，作为空白 Issue 的入口
contact_links:
  - name: Default Issue
    url: https://github.com/hust-open-atom-club/open-source-deadlines/issues/new
    about: 如果上述模板都不适用，请在此处提交。