
name: Lint Data Files

on:
  pull_request:
    paths:
      - 'data/**.yml'
  push:
    branches:
      - main # Or your default branch

jobs:
  lint-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML python-dateutil pytz

      - name: Run data validation script
        run: python .scripts/check_data.py
